spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/weather-service
    username: postgres
    password: 123
    options:
      driver: postgresql
      authentication: scram-sha-256
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
    url: jdbc:postgresql://localhost:5432/weather-service
    user: postgres
    password: 123
    enabled: true